In [1]:
import pandas as pd

dataframe_excel = pd.read_excel('BBC Results - Lesson 1 (MT12).xlsx', sheetname=0, header=0)

In [2]:
dataframe_excel.head()

,TIMESTAMP,Unnamed: 1,SLEEP,SCORE,Unnamed: 4
0,Date,Time,How many hours did you sleep last night?,Recognition Score,Temporal Memory Score
1,2012-12-11 18:16:31,2012-12-11 18:16:31,7,91,86
2,2012-12-13 14:31:16,2012-12-13 14:31:16,6.5,95,78
3,2012-12-13 14:31:30,2012-12-13 14:31:30,7,95,56
4,2012-12-13 14:32:01,2012-12-13 14:32:01,5,91,81

In [3]:
print(dataframe_excel)

                       TIMESTAMP                  Unnamed: 1  \
0                           Date                        Time
1            2012-12-11 18:16:31         2012-12-11 18:16:31
2            2012-12-13 14:31:16         2012-12-13 14:31:16
3            2012-12-13 14:31:30         2012-12-13 14:31:30
4            2012-12-13 14:32:01         2012-12-13 14:32:01
5            2012-12-13 14:34:07         2012-12-13 14:34:07
6            2012-12-13 14:34:16         2012-12-13 14:34:16
7            2012-12-13 14:35:50         2012-12-13 14:35:50
8            2012-12-13 14:36:36         2012-12-13 14:36:36
9            2012-12-13 14:44:30         2012-12-13 14:44:30
10           2012-12-13 14:44:57         2012-12-13 14:44:57
11           2012-12-13 14:48:38         2012-12-13 14:48:38
12           2012-12-13 14:54:44         2012-12-13 14:54:44
13           2012-12-13 14:58:49         2012-12-13 14:58:49
14           2012-12-13 15:01:56         2012-12-13 15:01:56
15           2012-12-13 15:03:48         2012-12-13 15:03:48
16           2012-12-13 15:07:31         2012-12-13 15:07:31
17           2012-12-13 15:08:34         2012-12-13 15:08:34
18           2012-12-13 15:12:18         2012-12-13 15:12:18
19           2012-12-13 15:30:14         2012-12-13 15:30:14
20           2012-12-13 16:00:34         2012-12-13 16:00:34
21           2012-12-13 16:07:53         2012-12-13 16:07:53
22           2012-12-13 16:08:13         2012-12-13 16:08:13
23           2012-12-13 18:48:48         2012-12-13 18:48:48
24           2012-12-13 20:19:32         2012-12-13 20:19:32
25           2012-12-14 01:42:31         2012-12-14 01:42:31
26           2012-12-14 01:55:20         2012-12-14 01:55:20
27           2012-12-14 10:58:26         2012-12-14 10:58:26
28           2012-12-16 11:43:14         2012-12-16 11:43:14
29           2012-12-16 11:58:39         2012-12-16 11:58:39
...                          ...                         ...
9127         2015-03-21 05:11:47         2015-03-21 05:11:47
9128         2015-03-23 19:59:37         2015-03-23 19:59:37
9129         2015-03-24 08:55:34         2015-03-24 08:55:34
9130         2015-03-24 13:56:19         2015-03-24 13:56:19
9131         2015-03-25 02:34:11         2015-03-25 02:34:11
9132         2015-03-25 09:55:20         2015-03-25 09:55:20
9133         2015-03-25 11:35:10         2015-03-25 11:35:10
9134         2015-03-25 13:43:30         2015-03-25 13:43:30
9135         2015-03-25 13:58:35         2015-03-25 13:58:35
9136         2015-03-25 13:58:54         2015-03-25 13:58:54
9137         2015-03-25 14:26:12         2015-03-25 14:26:12
9138         2015-03-25 14:38:43         2015-03-25 14:38:43
9139         2015-03-25 17:44:39         2015-03-25 17:44:39
9140         2015-03-26 17:27:39         2015-03-26 17:27:39
9141         2015-03-26 21:00:22         2015-03-26 21:00:22
9142         2015-03-28 13:03:38         2015-03-28 13:03:38
9143         2015-03-29 21:03:44         2015-03-29 21:03:44
9144         2015-03-29 22:00:47         2015-03-29 22:00:47
9145         2015-03-30 13:49:47         2015-03-30 13:49:47
9146         2015-03-30 14:53:06         2015-03-30 14:53:06
9147         2015-03-30 17:31:14         2015-03-30 17:31:14
9148         2015-03-30 22:16:57         2015-03-30 22:16:57
9149         2015-03-30 22:17:24         2015-03-30 22:17:24
9150         2015-03-30 23:18:25         2015-03-30 23:18:25
9151         2015-03-31 07:02:44         2015-03-31 07:02:44
9152         2015-03-31 19:22:14         2015-03-31 19:22:14
9153  2016-01-11 06:18:33.977000  2016-01-11 06:18:33.977000
9154  2016-05-20 13:48:06.779000  2016-05-20 13:48:06.779000
9155  2016-09-17 05:37:21.756000  2016-09-17 05:37:21.756000
9156  2016-09-17 05:37:42.625000  2016-09-17 05:37:42.625000

                                         SLEEP              SCORE  \
0     How many hours did you sleep last night?  Recognition Score
1                                            7                 91
2                                          6.5                 95
3                                            7                 95
4                                            5                 91
5                                          8.5                100
6                                            7                 87
7                                          6.5                 91
8                                          8.5                 95
9                                          6.5                 91
10                                           7                 91
11                                           8                100
12                                         7.5                100
13                                           8                 95
14                                           7                 79
15                                           5                 91
16                                           7                100
17                                         7.5                100
18                                         8.5                100
19                                           7                 83
20                                         8.5                 95
21                                           4                 91
22                                           4                 95
23                                         4.5                100
24                                           7                 70
25                                           8                 95
26                                           9                 45
27                                         5.5                100
28                                           9                 95
29                                           8                 83
...                                        ...                ...
9127                                        10                100
9128                                       5.5                 68
9129                                         8                 83
9130                                         7                 50
9131                                         8                100
9132                                         7                 68
9133                                         0                 45
9134                                         0                 88
9135                                         0                 90
9136                                         8                 90
9137                                         7                 60
9138                                       7.5                 84
9139                                       6.5                 65
9140                                       2.5                100
9141                                         7                 95
9142                                      11.5                 95
9143                                         0                NaN
9144                                         8                 60
9145                                         9                 91
9146                                         8                 75
9147                                         3                 60
9148                                         8                 95
9149                                         8                 95
9150                                         7                 70
9151                                       7.5                 79
9152                                         8                  0
9153                                         8                NaN
9154                                         1                 ee
9155                                       5.5                NaN
9156                                       5.5                NaN

                 Unnamed: 4
0     Temporal Memory Score
1                        86
2                        78
3                        56
4                        81
5                        75
6                        80
7                        95
8                        91
9                        81
10                       86
11                       79
12                       87
13                       73
14                       78
15                       81
16                       95
17                       70
18                       95
19                       90
20                       73
21                       86
22                       73
23                      100
24                       82
25                      100
26                       54
27                       79
28                       78
29                       70
...                     ...
9127                     83
9128                     58
9129                     90
9130                    100
9131                     87
9132                     68
9133                     54
9134                    100
9135                     90
9136                     90
9137                     50
9138                     72
9139                     70
9140                    100
9141                     86
9142                     73
9143                    NaN
9144                     50
9145                     63
9146                     68
9147                     65
9148                     86
9149                     86
9150                     94
9151                     75
9152                      0
9153                    NaN
9154                     ee
9155                    NaN
9156                    NaN

[9157 rows x 5 columns]